### ISSUE TITLE
Not loading data

### ISSUE THREAD

**Issue by eterradas** [VivekPanyam/Plotter#1]
After

$git clone ...
$npm install express
$npm install socket.io
$nodejs index.js
$curl -X GET -H "Content-Type: application/json" -d '{"Signups":{"Web":12,"Mobile":10}}' http://localhost:8000/data/my_api_key/json

But in http://localhost:8000 data is not displayed. 
(Checked with Chromium and Firefox browsers)

Any dependency missing?

**Comment by VivekPanyam** [comment]
Right now, the JSON should actually be in the URL. Make a GET request to http://localhost:8000/data/my_api_key/{"Signups":{"Web":12,"Mobile":10}}.

This will be cleaned up in an upcoming commit.

**Comment by eterradas** [comment]
Thanks will try it.
